version: '3.7'

services:
  postgres:
    image: library/postgres:12-alpine
    container_name: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: space_db
